
# generated by DI factory
class Conversion:

    def __init__(self, fromType, toType, fn):
        self._fromType = fromType
        self._toType = toType
        self._fn = fn

    def get_type(self):
        return self._fromType

    # if want to add additional conversions manually, maybe needs removed?
    def set_fn(self, fnConvert):
        self._fn = fnConvert

    def get_fn(self, toType):
        return self._fn
    
    def __str__(self):
        result = 'From Type: {}\n'.format(self._fromType)
        result += 'To Type: {}\n'.format(self._toType)
        result += '\tEquation: {}\n'.format(str(self._fn))
        return result

